alias ga.="git add ."
alias sl="storm list"
alias e="ember"
alias vgi="vagrant init"
alias vgl="vagrant box list"
alias vgu="vagrant up"
alias gdp="grunt deploy"
alias dl="diskutil list"
alias du="diskutil unmountDisk"
alias emdp="ember b -prod && grunt deploy"
alias grh="git reset --hard HEAD"
alias nv="npm version"
alias grc="git rebase --continue"
alias gmt="git mergetool"
alias nibi="ni && bi"
alias gk="git checkout"
alias fl="forever list"
alias fst="forever start"
alias fsp="forever stop"
alias tzxf="tar zxf"
alias fuck='eval $(thefuck $(fc -ln -1)); history -r'
alias gpt="git push && git push --tags"
alias nr="npm run"
alias jsa="jshint ."
alias nvp="npm version patch"
alias nvmi="npm version minor"
alias nvmj="npm version major"
alias gch="git checkout"
alias emss="ember server --environment=staging"
alias embp="ember build --environment=production"
alias ems="ember server"
alias emg="ember generate"
alias nis="npm install --save"
alias bis="bower install --save"
alias sba='source ~/.bash_aliases'
alias gpht='git push origin --tags'
alias nig='npm install -g'
alias nu='npm uninstall'
alias nug='npm uninstall -g'
alias grsd='grunt serve:dist'
alias grb='grunt build'
alias bi="bower install"
alias grs='grunt serve'
alias gau='git add -u'
alias gr='grunt'
alias grr='grunt release'
alias ni='npm install'
alias ns='npm start'
alias nt='npm test'
alias gpi='git pull && npm install'
alias dig='dig +multi'
alias g=git
alias hman='man --html=browser-pause'
alias la='ls -al'
alias ll='ls -lh'
alias ping='ping -n'
alias rsync='rsync -h'
alias wgoat='wget'
alias whois='whois -H'
alias ls="ls -G"
alias q="exit"
alias a="clear"
alias gss="git status"
alias gd="git diff"
alias gdw="git diff --color-words"
alias ga="git add -p"
alias gg="git grep -n --color"
alias gc="git commit"
alias gfo="git fetch origin"
alias gro="git rebase origin/master"
alias gcm="git checkout master"
alias grod="git rebase origin/development"
alias gcd="git checkout development"
alias gcb="git checkout -b"
alias gst="git stash"
alias gsp="gs pop"
alias ra="sudo apachectl restart"
alias gb="git branch"
alias gl="git lola"
alias gpl="git pull"
alias gph="echo //////————— push it real good! ————///// && git push"
alias cs="cd ~/src"
alias consolergx="echo 'console.log(.*?);' | pbcopy"
alias gcam=commitWithMessage
alias zipc=zipCurrentFolder
