alias ami="ssh -l ec2-user -i ~/.ssh/drg-euw1-cider-development.pem  euw1a-web02.dresources.com"
alias fl="forever list"
alias fst="forever start"
alias fsp="forever stop"
alias tzxf="tar zxf"
alias fuck='eval $(thefuck $(fc -ln -1)); history -r'
alias gpt="git push --tags"
alias nr="npm run"
alias jsa="jshint ."
alias nvp="npm version patch"
alias nvmi="npm version minor"
alias nvmj="npm version major"
alias gch="git checkout"
alias emss="ember server --environment=staging"
alias embp="ember build --environment=production"
alias ems="ember server"
alias emg="ember generate"
alias nis="npm install --save"
alias bis="bower install --save"
alias sba='source ~/.bash_aliases'
alias gpht='git push origin --tags'
alias nig='npm install -g'
alias nu='npm uninstall'
alias nug='npm uninstall -g'
alias grsd='grunt serve:dist'
alias grb='grunt build'
alias bi="bower install"
alias grs='grunt serve'
alias gau='git add -u'
alias gr='grunt'
alias grr='grunt release'
alias ni='npm install'
alias ns='npm start'
alias nt='npm test'
alias gpi='git pull && npm install'
alias smv='sudo ~/src/utility-scripts/manage-vhost.sh'
alias apt='aptitude'
alias dig='dig +multi'
alias dquilt='QUILT_PATCHES=debian/patches quilt'
alias dstat='dstat --bw'
alias dux='du -xm --max-depth=1'
alias e="$EDITOR"
alias g=git
alias gdb='gdb -silent'
alias hman='man --html=browser-pause'
#alias gnutls-cli="gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt"
alias la='ls -al'
alias ll='ls -lh'
alias massif='valgrind --tool=massif --depth=5 --alloc-fn={g_malloc,g_realloc,g_try_malloc,g_malloc0,g_mem_chunk_alloc}'
alias mysql='mysql --pager'
alias ping='ping -n'
alias pol='apt-cache policy'
alias rsync='rsync -h'
alias units='units --verbose'
alias wgoat='wget'
alias whois='whois -H'
alias xc='xclip -selection clipboard -in'
alias xp='xclip -selection clipboard -out'
alias xse='tail --follow=name ~/.xsession-errors -n 0'
alias ls="ls -G"
#alias vi="mvim"
alias q="exit"
alias a="clear"
alias gss="git status"
alias gd="git diff"
alias gdw="git diff --color-words"
alias ga="git add -p"
alias gg="git grep -n --color"
alias gc="git commit"
alias gfo="git fetch origin"
alias gro="git rebase origin/master"
alias gcm="git checkout master"
alias grod="git rebase origin/development"
alias gcd="git checkout development"
alias gcb="git checkout -b"
alias gst="git stash"
alias gsp="gs pop"
alias ra="sudo apachectl restart"
alias gb="git branch"
alias gl="git lola"
alias gpl="git pull"
alias gph="echo //////————— push it real good! ————///// && git push"
alias cs="cd ~/src"
alias consolergx="echo 'console.log(.*?);' | pbcopy"
alias gcam=commitWithMessage
alias zipc=zipCurrentFolder
