#!/usr/bin/env sh

# taps
brew tap gapple/services
brew tap homebrew/boneyard
brew tap homebrew/bundle
brew tap homebrew/core
brew tap neovim/neovim
brew tap rstacruz/backup
brew tap tomanthony/brews

# packages
brew install ack
brew install antigen
brew install autoconf
brew install automake
brew install bash
brew install bash-completion
brew install boost
brew install cairo
brew install cmake
brew install czmq
brew install direnv
brew install dirmngr
brew install dnsmasq
brew install duplicity
brew install eot-utils
brew install fasd
brew install flyway
brew install fontconfig
brew install fontforge
brew install freetype
brew install gdbm
brew install geoip
brew install gettext
brew install git
brew install git-extras
brew install glew
brew install glib
brew install glm
brew install gmp
brew install gnu-sed
brew install gnupg
brew install gnupg2
brew install gnutls
brew install gobject-introspection
brew install gource
brew install gpg-agent
brew install harfbuzz
brew install htop-osx
brew install icu4c
brew install itermocil
brew install jasper
brew install jenv
brew install jpeg
brew install jq
brew install leptonica
brew install lftp
brew install libassuan
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libksba
brew install libpng
brew install librsync
brew install libsodium
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libyaml
brew install maven
brew install mongodb
brew install mono64
brew install mysql
brew install ncdu
brew install netpbm
brew install nettle
brew install nginx
brew install nmap
brew install node
brew install oniguruma
brew install openssl
brew install pango
brew install parallel
brew install passenger
brew install pcre
brew install peco
brew install pgcli
brew install phantomjs
brew install pinentry
brew install pixman
brew install pkg-config
brew install popt
brew install postgresql
brew install pth
brew install python
brew install qemu
brew install readline
brew install ren
brew install rename
brew install ruby
brew install s-lang
brew install samba
brew install sdl2
brew install sdl2_image
brew install sqlite
brew install ssed
brew install stormssh
brew install the_silver_searcher
brew install tree
brew install unixodbc
brew install webp
brew install wget
brew install xz
brew install yarn
brew install zeromq
brew install zsh
